[workspace]
resolver = "2"

members = [
   "lc-0001-twosum",
   "lc-0002-addtwonumbers",
   "lc-0011-mostwater", "lc-0432-all-one-data-structure", "lc-0641-circular-dequeue/lc-0641-circular-dequeue",
   "lc-1371-longestsubstreven",
]
